### ISSUE TITLE
app not installed as package appears to be invalid

### ISSUE THREAD

**Issue by sailorworks** [NullPounce/pounce-keys#26]
First I installed from https://github.com/NullPounce/pounce-keys/releases the 2.0_PounceKeys-Discord.apk. Then I installed the apktool and apparently there is no gui version available for Mac. So I just used cli, now to decompile the file downloaded I ran the command `apktool d path_to_ 2.0_PounceKeys-Discord.apk `, it gave me the folder as seen in the video, made changes accordingly. To compile it I ran the command `apktool b path_to_ 2.0_PounceKeys-Discord_folder` , but now as seen in the video the apk file that is compiled into apk is  2.0_PounceKeys-Discord-signed.apk  but just got  2.0_PounceKeys-Discord.apk. Then I transferred the apk file to my android phone and tried installing it, but the above message popped.

I wonder what could have been gone wrong.

**Comment by NullPounce** [comment]
That's because you are not signing the APK or ZIP aligning it, Please use the latest GUI builder with JDK19 or use APK Tool GUI to build/decompile the APK.

https://github.com/NullPounce/pounce-keys/releases/tag/PounceKey's

PounceKeysBuilder_2.0.rar

If you insist on CLI you will need to download SignAPK.jar and uber-apk-signer.jar and zipalign with a key.jks file, this can all be found in prior builder versions but the APKtpplGUI program this does all of this for you.
